# docker-compose from Phala Network Official Repo !   Collation By Suge

version: "2"

x-defaults: &defaults
  volumes: &default-volume-config
    - /var/khala-dev-node/prb_data:/var/data

services:
  data_provider:
    image: phalanetwork/prb:next
    hostname: data_provider
    network_mode: host
    restart: always
    volumes: *default-volume-config
    logging:
      options:
        # saved log sizes
        # max-size: "1g"
        max-size: "500m"
    environment:
      # The module to be started
      - PHALA_MODULE=data_provider

      # Application environment, set to development to put the application in development mode
      - NODE_ENV=development

      # Logging level
      - PHALA_LOGGER_LEVEL=debug

      # Same environment variables to be consistent with the PRB's lifecycle
      - PHALA_BRIDGE_IDENTITY=staging

      # Substrate RPC for WebSocket endpoints to relay chains (e.g., for Khala, it is Kusama)
      - PHALA_PARENT_CHAIN_ENDPOINT=ws://127.0.0.1:9945

      # WebSocket endpoints pointing to the Substrate RPC of the subchain (here pointing to khala).
      - PHALA_CHAIN_ENDPOINT=ws://127.0.0.1:9944

      # Multiple addresses for libp2p's listening address (https://github.com/libp2p/specs/tree/master/addressing)
      # Defaults to '/ip4/0.0.0.0/tcp/0, /ip6/::/tcp/0', which means listening to a random port on each interface.
      # Only TCP protocol is supported. Use commas between addresses. Configuring 127.0.0.1 may not be discovered
      # - PHALA_WALKIE_LISTEN_ADDRESSES=/ip4/127.0.0.1/tcp/28888,/ip6/::/tcp/28889
      - PHALA_WALKIE_LISTEN_ADDRESSES=/ip4/0.0.0.0/tcp/28888,/ip6/::/tcp/28889

      # The multi-add list of boot nodes for peer discovery defaults to "/ip4/0.0.0.0/tcp/18888, /ip6/::/tcp/28889", which means there are no boot nodes.
      # Only TCP protocol is supported. Use commas between addresses.
      # - PHALA_WALKIE_BOOT_NODES=/ip4/0.0.0.0/tcp/18888, /ip6/::/tcp/28889
      - PHALA_WALKIE_BOOT_NODES=/ip4/0.0.0.0/tcp/18888,/ip6/::/tcp/18889

      # The maximum memory used by BLOB service session is 64G
      - PHALA_LIFECYCLE_BLOB_SERVER_SESSION_MAX_MEMORY=64

      # The default path to store the identity key is ". /data/keys/id", the default storage . /data/keys/id
      # - PHALA_PEER_ID_PREFIX=. /data/keys/id

      # the blob server, defaults to 8012
      # PHALA_DATA_PROVIDER_LOCAL_SERVER_PORT=8012

      # The path to database, defaults to '. /data/0'.
      # - PHALA_LOCAL_DB_PATH=

    entrypoint:
      - "node"
      - "--trace-warnings"
      - "--experimental-json-modules"
      - "--es-module-specifier-resolution=node"
      - "--harmony-top-level-await"
      # - "--trace-gc"
      # - "--expose-gc"
      # - "--no-compilation-cache"
      # - "--max-old-space-size=10240"
      # - "--max-heap-size=100"
      # - "--no-always-promote-young-mc"
      - "dist/index"

  monitor:
    image: phalanetwork/prb-monitor:next
    hostname: monitor
    network_mode: host
    environment:
      - NS_FETCH=fetch
      - NEXT_PUBLIC_NS_LIST=default
      - PTP_BOOT_NODES=/ip4/127.0.0.1/tcp/28888
    # ports:
    # - "3000:3000"

# services:
  redis-q:
    network_mode: host
    image: redis:alpine
    hostname: redis-q
    restart: always
    logging:
      options:
        max-size: "1g"
    command: ["redis-server", "--port", "63792", "--appendonly", "no", '--save', '']
    # ports:
    # - "63792:63792"

  arena:
    network_mode: host
    image: phalanetwork/prb:next
    hostname: arena
    restart: always
    depends_on:
      - redis-q
    environment:
      - PHALA_MODULE=utils/arena
      - NODE_ENV=development
      - PHALA_LOGGER_LEVEL=debug
      - PHALA_NAMESPACE=default
      - REDIS_ENDPOINT=redis://127.0.0.1:63792/
    # ports:
    # - "4567:4567"

  trade:
    network_mode: host
    image: phalanetwork/prb:next
    hostname: trade
    restart: always
    volumes: *default-volume-config
    logging:
      options:
        # max-size: "1g"
        max-size: "500m"
    depends_on:
      - redis-q
    environment:
      - PHALA_MODULE=trade
      - NODE_ENV=development
      - PHALA_DB_NAMESPACE=default
      - PHALA_DB_FETCH_NAMESPACE=fetch
      - PHALA_DB_ENDPOINT=redis://127.0.0.1:6666
      - PHALA_LOGGER_LEVEL=debug
      - PHALA_PARENT_CHAIN_ENDPOINT=ws://127.0.0.1:9945
      - PHALA_CHAIN_ENDPOINT=ws://127.0.0.1:9944
      - PHALA_Q_REDIS_ENDPOINT=redis://127.0.0.1:63792/
    entrypoint:
      - "node"
      - "--trace-warnings"
      - "--experimental-json-modules"
      - "--es-module-specifier-resolution=node"
      - "--harmony-top-level-await"
      # - "--max-old-space-size=10240"
      - "dist/index"

  lifecycle:
    network_mode: host
    image: phalanetwork/prb:next
    hostname: lifecycle
    restart: always
    depends_on:
      - redis-q
    volumes: *default-volume-config
    logging:
      options:
        # max-size: "1g"
        max-size: "500m"
    environment:
      # default is false
      # - PHALA_SYNC_ONLY=true
      # - PHALA_SYNC_ONLY=false
      - PHALA_MODULE=lifecycle
      - NODE_ENV=development
      - PHALA_LOGGER_LEVEL=debug

      # To be consistent with the same environment variables of dp's data_provider
      - PHALA_BRIDGE_IDENTITY=staging

      - PHALA_Q_REDIS_ENDPOINT=redis://127.0.0.1:63792/

      # Substrate RPC for WebSocket endpoints to relay chains (e.g., for Khala, it is Kusama)
      - PHALA_PARENT_CHAIN_ENDPOINT=ws://127.0.0.1:9945
      # WebSocket endpoints pointing to the Substrate RPC of the subchain (here pointing to khala).
      - PHALA_CHAIN_ENDPOINT=ws://127.0.0.1:9944      

      # The size of LRU cache, defaults to 5000.
      - PHALA_LRU_CACHE_SIZE=50
      # The maximum time (in milliseconds) for items in the LRU cache, defaults to 30 minutes.
      - PHALA_LRU_CACHE_MAX_AGE=90000

      - PHALA_PRPC_REQUEST_TIMEOUT=60000

      # should be the maximum number of workers that lifecycle can synchronize at one time at the same point in time
      - PHALA_RUNNER_MAX_WORKER_NUMBER=150

      # Should enter configuration mode, which will only start the API to add/modify saved pools and workers
      # - PHALA_ENFORCE_MIN_BENCH_SCORE=true

      # - PHALA_WALKIE_BOOT_NODES=/ip4/10.87.0.51/tcp/28888/p2p/QmbgiLdgeBhVmCfDtrFzC158HCkRTC4J38tZay2T3uxjtJ,/ip4/10.87.0.52/tcp/28888/ p2p/QmWhwPfb2VtuBQtrepw9shoafGmvnXdKu8fNq7Yfw32jCN
      - PHALA_WALKIE_BOOT_NODES=/ip4/127.0.0.1/tcp/28888/p2p/{YOUR DATA PROVIDERSs PEERID}
      # - PHALA_WALKIE_LISTEN_ADDRESSES=/ip4/127.0.0.1/tcp/29888,/ip6/::/tcp/29889
      - PHALA_WALKIE_LISTEN_ADDRESSES=/ip4/0.0.0.0/tcp/29888,/ip6/::/tcp/29889

    mem_swappiness: 70
    entrypoint:
      - "node"
      - "--trace-warnings"
      - "--experimental-json-modules"
      - "--es-module-specifier-resolution=node"
      - "--harmony-top-level-await"
      - "dist/index"
    # ports:
    # - "29888:29888"
